services:
  mongo:
    image: mongo
    container_name: mongo-data
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-volume:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-ui
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123

  app:
    build: .
    container_name: sensor-batch-loader
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: mongoadmin
      MONGO_PASS: secret
      MONGO_AUTH_DB: admin
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "scripts/load_script.py"]

volumes:
  mongo-volume:

